### ISSUE TITLE
Generate docset for WP-CLI v2.0.0?

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/dash-docset-generator#5]
@ptrkcsk Does a docset need to be generated for WP-CLI v2.0.0?

Also, what's the process for publishing the docset? Can we document that in the README?

**Comment by ptrkcsk** [comment]
Yeah! I was waiting to see v2.x released of wp-cli/handbook. Am I correct in assuming that wp-cli/handbook releases correspond to a matching release of wp-cli/wp-cli? If so, will that continue to be the case?

I'd be happy to add the publishing process to the readme. In the meantime, here's [Dash's documentation for user-generated docsets](https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset).

**Comment by danielbachhuber** [comment]
> Am I correct in assuming that wp-cli/handbook releases correspond to a matching release of wp-cli/wp-cli? If so, will that continue to be the case?

Yes, and correct. I've tagged the v2.0.0 release: https://github.com/wp-cli/handbook/releases/tag/v2.0.0

@schlessera Can you make sure tagging a handbook release is a part of the release process?

> I'd be happy to add the publishing process to the readme. In the meantime, here's Dash's documentation for user-generated docsets.

Cool, sounds good. Linking to that reference would be sufficient, I think.

**Comment by ptrkcsk** [comment]
Pull request created: Kapeli/Dash-User-Contributions#2047

**Comment by ptrkcsk** [comment]
The docset for v2.0.0 is now available on Dash.

**Comment by ptrkcsk** [comment]
Readme updated.
